language: python

python:
  - "3.7-dev"  # 3.7 development branch


install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - pytest --with coverage --cover-package=app

after success:
  - coveralls
  

  
