language: python
os: windows

python:
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
virtualenv:
  system_site_packages: true
# command to run tests
script:
  - pytest
